/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmsimulator;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lokesh
 */
public class Additional extends javax.swing.JFrame {

    private PersonalBean pb=null;
    /**
     * Creates new form Additional
     */
    public Additional() {
        initComponents();
       this.setLocationRelativeTo(null);
        CreateCursor();
        createHandCursor();
    }

         public Connection con;

    public void setCon(Connection con) {
        this.con = con;
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
       public void setPB(PersonalBean pb)
    {
        this.pb=pb;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        senion = new javax.swing.ButtonGroup();
        existing = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        religion = new javax.swing.JComboBox<>();
        category = new javax.swing.JComboBox<>();
        equalification = new javax.swing.JComboBox<>();
        income = new javax.swing.JComboBox<>();
        occupation = new javax.swing.JComboBox<>();
        pno = new javax.swing.JTextField();
        ano = new javax.swing.JTextField();
        syes = new javax.swing.JRadioButton();
        sno = new javax.swing.JRadioButton();
        eyes = new javax.swing.JRadioButton();
        eno = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        worning = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 22, 25));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        jPanel1.setPreferredSize(new java.awt.Dimension(757, 730));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(30, 79, 36));
        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Additional Details");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(43, 11, 202, 23);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(230, 30, 310, 40);

        jPanel5.setBackground(new java.awt.Color(0, 22, 25));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel5.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Page 2");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(230, 10, 90, 22);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Religion :");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(74, 54, 55, 23);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Income :");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(74, 162, 66, 23);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Qualification");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(74, 245, 79, 17);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Category :");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(74, 106, 79, 23);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Occupation :");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(70, 290, 79, 17);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("PAN Number :");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(70, 330, 87, 17);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Aadhar Number :");
        jPanel5.add(jLabel28);
        jLabel28.setBounds(70, 370, 111, 17);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Existing Account :");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(70, 450, 111, 17);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Educational :");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(74, 216, 79, 19);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("Senior Citizen :");
        jPanel5.add(jLabel31);
        jLabel31.setBounds(70, 410, 111, 20);

        religion.setBackground(new java.awt.Color(30, 79, 36));
        religion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        religion.setForeground(new java.awt.Color(255, 255, 255));
        religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Hindu", "Muslim", "Sikh", "Christian", "Other" }));
        religion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(religion);
        religion.setBounds(340, 40, 172, 30);

        category.setBackground(new java.awt.Color(30, 79, 36));
        category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        category.setForeground(new java.awt.Color(255, 255, 255));
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "General", "OBC", "SC", "ST", "Other" }));
        category.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(category);
        category.setBounds(340, 100, 172, 30);

        equalification.setBackground(new java.awt.Color(30, 79, 36));
        equalification.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        equalification.setForeground(new java.awt.Color(255, 255, 255));
        equalification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Non-Graduate", "Graduate", "Post-Graduate", "Doctrate", "Other" }));
        equalification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(equalification);
        equalification.setBounds(340, 210, 172, 30);

        income.setBackground(new java.awt.Color(30, 79, 36));
        income.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        income.setForeground(new java.awt.Color(255, 255, 255));
        income.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Null", "<150000", "<250000", "<500000", "<1000000", ">1000000" }));
        income.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(income);
        income.setBounds(340, 150, 172, 30);

        occupation.setBackground(new java.awt.Color(30, 79, 36));
        occupation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        occupation.setForeground(new java.awt.Color(255, 255, 255));
        occupation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Salaried", "Self-Employed", "Business", "Student", "Retired", "Other" }));
        occupation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(occupation);
        occupation.setBounds(340, 280, 172, 30);

        pno.setBackground(new java.awt.Color(0, 22, 25));
        pno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pno.setForeground(new java.awt.Color(255, 255, 255));
        pno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pno.setCaretColor(new java.awt.Color(30, 79, 36));
        pno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel5.add(pno);
        pno.setBounds(340, 330, 172, 20);

        ano.setBackground(new java.awt.Color(0, 22, 25));
        ano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ano.setForeground(new java.awt.Color(255, 255, 255));
        ano.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ano.setCaretColor(new java.awt.Color(30, 79, 36));
        ano.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoActionPerformed(evt);
            }
        });
        jPanel5.add(ano);
        ano.setBounds(340, 370, 172, 20);

        syes.setBackground(new java.awt.Color(0, 22, 25));
        senion.add(syes);
        syes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        syes.setForeground(new java.awt.Color(255, 255, 255));
        syes.setText("Yes");
        jPanel5.add(syes);
        syes.setBounds(350, 410, 56, 25);

        sno.setBackground(new java.awt.Color(0, 22, 25));
        senion.add(sno);
        sno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sno.setForeground(new java.awt.Color(255, 255, 255));
        sno.setText("No");
        jPanel5.add(sno);
        sno.setBounds(450, 410, 43, 25);

        eyes.setBackground(new java.awt.Color(0, 22, 25));
        existing.add(eyes);
        eyes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eyes.setForeground(new java.awt.Color(255, 255, 255));
        eyes.setText("Yes");
        jPanel5.add(eyes);
        eyes.setBounds(350, 450, 47, 25);

        eno.setBackground(new java.awt.Color(0, 22, 25));
        existing.add(eno);
        eno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eno.setForeground(new java.awt.Color(255, 255, 255));
        eno.setText("No");
        jPanel5.add(eno);
        eno.setBounds(450, 450, 43, 25);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(100, 110, 550, 510);

        jPanel6.setBackground(new java.awt.Color(30, 79, 36));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(null);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Next");
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(jLabel34);
        jLabel34.setBounds(10, 0, 68, 40);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(650, 640, 90, 40);

        worning.setForeground(new java.awt.Color(255, 0, 0));
        worning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        worning.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(worning);
        worning.setBounds(260, 80, 251, 15);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setPreferredSize(new java.awt.Dimension(120, 39));
        jPanel7.setLayout(null);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MINUS.PNG"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel8);
        jLabel8.setBounds(0, 0, 34, 36);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CANCEL.PNG"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel9);
        jLabel9.setBounds(52, 0, 32, 36);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(650, 20, 86, 36);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
       jPanel6.setBackground(new Color(45, 119, 54));
        PreparedStatement ps=null;
        if(religion.getSelectedItem().equals("Select"))
             worning.setText("Please Select your Religion!!");else{
              if(category.getSelectedItem().equals("Select"))
                 worning.setText("Please Select your Category!!");else{
                  if(income.getSelectedItem().equals("Select"))
                   worning.setText("Please Select your income!!");else{
                      if(equalification.getSelectedItem().equals("Select"))
                        worning.setText("Please Select your Eductional Qualification!!");else{
                          if(occupation.getSelectedItem().equals("Select"))
                            worning.setText("Please Select your Occupation!!");else{
                              if(pno.getText().equals(""))
                                worning.setText("Please enter your Pin Number!!");else{
                                  if(ano.getText().equals(""))
                                      worning.setText("Please enter your Aadhar Number!!");else{
                                     if(!syes.isSelected()&&!sno.isSelected())
                                         worning.setText("Please Select Senior Citizen Option!!");else{
                                           if(!eyes.isSelected()&&!eno.isSelected())
                                            worning.setText("Please Select Existing Account Option!!");else{
                                                        Connections c=new Connections();                                                        
                                               try {
                                                                      
                                                ps=con.prepareStatement("insert into user values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);");
                                                  ps.setInt(1,pb.getNum());
                                                  ps.setString(2,pb.getName());
                                                   ps.setString(3,pb.getFathername());
                                                   ps.setString(4,pb.getDay());
                                                   ps.setString(5,pb.getMonth());
                                                   ps.setString(6,pb.getYear());
                                                   ps.setString(7,pb.getGender());
                                                   ps.setString(8,pb.getEmail());
                                                   ps.setString(9,pb.getAddress());
                                                   ps.setString(10,pb.getCity());
                                                   ps.setString(11,pb.getPcode());
                                                   ps.setString(12,pb.getState());
                                                   ps.setString(13,(String)religion.getSelectedItem());
                                                   ps.setString(14,(String)category.getSelectedItem());
                                                   ps.setString(15,(String)income.getSelectedItem());
                                                   ps.setString(16,(String)equalification.getSelectedItem());
                                                   ps.setString(17,(String)occupation.getSelectedItem());
                                                   ps.setString(18,pno.getText());
                                                   ps.setString(19,ano.getText());
                                                      if(syes.isSelected())
                                                   ps.setString(20,"Yes");
                                                      else
                                                   ps.setString(20,"No"); 
                                                      if(eyes.isSelected())
                                                   ps.setString(21,"Yes");
                                                      else
                                                    ps.setString(21,"NO");
                                                    
                                                     ps.executeUpdate();
                                   
                                             
                                                         AccountInfo ai=new AccountInfo();
                                                         ai.setVisible(true);
                                                         ai.setPB(pb);
                                                         ai.setCon(con);
                                                         this.setVisible(false);
                                                     
                                                     } catch (SQLException ex) {
                                                   Logger.getLogger(Additional.class.getName()).log(Level.SEVERE, null, ex);
                                               }
                                                   }
                                                 }
                                               }
                                            }
                                           }
                                         }
                                    }                       
                              }
                }
    }//GEN-LAST:event_jPanel6MouseClicked

     public void CreateCursor()
    {
        Toolkit toolkit=Toolkit.getDefaultToolkit();
        Image img=toolkit.getImage("CC4.png");
        Point point=new Point(0,0);
        Cursor cursor=toolkit.createCustomCursor(img, point,"CC4");
       
        this.setCursor(cursor);
     
        jPanel1.setCursor(cursor);
       
        worning.setCursor(cursor);
    
      
    }
    
    public void createHandCursor()
    {
       Toolkit t=Toolkit.getDefaultToolkit();
        Image i=t.getImage("CC3.png");
        Point p=new Point(0,0);
        Cursor c=t.createCustomCursor(i, p,"CC3");
        jLabel8.setCursor(c);
        jLabel9.setCursor(c);
        syes.setCursor(c);
        sno.setCursor(c);
        eyes.setCursor(c);
        eno.setCursor(c);
        jPanel6.setCursor(c);
        jLabel34.setCursor(c);
        religion.setCursor(c);
        category.setCursor(c);
        income.setCursor(c);
        equalification.setCursor(c);
        occupation.setCursor(c);
        
    }
    
    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
    jPanel6.setBackground(new Color(18, 46, 21));
    
    }//GEN-LAST:event_jPanel6MousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setState(LogIn.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
       jPanel6.setBackground(new Color(45, 119, 54));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
      jPanel6.setBackground(new Color(30,79,36));
    }//GEN-LAST:event_jPanel6MouseExited

    private void anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Additional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Additional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Additional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Additional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Additional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ano;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JRadioButton eno;
    private javax.swing.JComboBox<String> equalification;
    private javax.swing.ButtonGroup existing;
    private javax.swing.JRadioButton eyes;
    private javax.swing.JComboBox<String> income;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JComboBox<String> occupation;
    private javax.swing.JTextField pno;
    private javax.swing.JComboBox<String> religion;
    private javax.swing.ButtonGroup senion;
    private javax.swing.JRadioButton sno;
    private javax.swing.JRadioButton syes;
    private javax.swing.JLabel worning;
    // End of variables declaration//GEN-END:variables
}
