/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmsimulator;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lokesh
 */
public class PersonalDetail extends javax.swing.JFrame {

    /**
     * Creates new form PersonalDetail
     */
    public PersonalDetail() {
        initComponents();
       this.setLocationRelativeTo(null);
       CreateCursor();
       createHandCursor();
    }
        public Connection con;

    public void setCon(Connection con) {
        this.con = con;
    }
     int num=0;
    PersonalBean pb=new PersonalBean();
     /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        mstatus = new javax.swing.ButtonGroup();
        UI = new atmsimulator.UI();
        jPanel1 = new javax.swing.JPanel();
        appno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UI1 = new atmsimulator.UI();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        eaddress = new javax.swing.JTextField();
        unmarried = new javax.swing.JRadioButton();
        married = new javax.swing.JRadioButton();
        other = new javax.swing.JRadioButton();
        state = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        pcode = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        worning = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        UI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));
        UI.setPreferredSize(new java.awt.Dimension(757, 735));

        jPanel1.setBackground(new java.awt.Color(30, 79, 36));

        appno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        appno.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Application Form NO : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appno, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(appno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        UI1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        UI1.setPreferredSize(new java.awt.Dimension(757, 735));
        UI1.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Page 1 : Personal Detail");
        UI1.add(jLabel20);
        jLabel20.setBounds(165, 12, 225, 22);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Marital Status :");
        UI1.add(jLabel21);
        jLabel21.setBounds(57, 286, 92, 17);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Name :");
        UI1.add(jLabel22);
        jLabel22.setBounds(57, 80, 55, 17);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Email Address :");
        UI1.add(jLabel23);
        jLabel23.setBounds(57, 243, 92, 17);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Fathers Name :");
        UI1.add(jLabel24);
        jLabel24.setBounds(57, 124, 93, 17);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Gender :");
        UI1.add(jLabel25);
        jLabel25.setBounds(60, 197, 92, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Date Of Birth :");
        UI1.add(jLabel26);
        jLabel26.setBounds(57, 167, 88, 17);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Address :");
        UI1.add(jLabel27);
        jLabel27.setBounds(57, 329, 92, 17);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("City :");
        UI1.add(jLabel28);
        jLabel28.setBounds(57, 374, 92, 19);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("State :");
        UI1.add(jLabel29);
        jLabel29.setBounds(57, 466, 92, 17);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Pin Code :");
        UI1.add(jLabel30);
        jLabel30.setBounds(57, 420, 92, 17);

        name.setBackground(new java.awt.Color(0, 22, 25));
        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        name.setCaretColor(new java.awt.Color(30, 79, 36));
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UI1.add(name);
        name.setBounds(259, 78, 223, 19);

        fname.setBackground(new java.awt.Color(0, 22, 25));
        fname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        fname.setCaretColor(new java.awt.Color(30, 79, 36));
        fname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UI1.add(fname);
        fname.setBounds(259, 123, 223, 19);

        day.setBackground(new java.awt.Color(30, 79, 36));
        day.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        day.setForeground(new java.awt.Color(255, 255, 255));
        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UI1.add(day);
        day.setBounds(288, 164, 44, 23);

        month.setBackground(new java.awt.Color(30, 79, 36));
        month.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        month.setForeground(new java.awt.Color(255, 255, 255));
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        month.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UI1.add(month);
        month.setBounds(381, 164, 44, 23);

        year.setBackground(new java.awt.Color(30, 79, 36));
        year.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        year.setForeground(new java.awt.Color(255, 255, 255));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0000", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010" }));
        UI1.add(year);
        year.setBounds(460, 164, 70, 23);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("Year");
        UI1.add(jLabel31);
        jLabel31.setBounds(429, 164, 27, 23);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("Month");
        UI1.add(jLabel32);
        jLabel32.setBounds(336, 164, 41, 23);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText("Day");
        UI1.add(jLabel33);
        jLabel33.setBounds(259, 164, 25, 23);

        male.setBackground(new java.awt.Color(0, 22, 25));
        gender.add(male);
        male.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        UI1.add(male);
        male.setBounds(260, 200, 51, 25);

        female.setBackground(new java.awt.Color(0, 22, 25));
        gender.add(female);
        female.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        UI1.add(female);
        female.setBounds(360, 200, 67, 25);

        eaddress.setBackground(new java.awt.Color(0, 22, 25));
        eaddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eaddress.setForeground(new java.awt.Color(255, 255, 255));
        eaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        eaddress.setCaretColor(new java.awt.Color(30, 79, 36));
        eaddress.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UI1.add(eaddress);
        eaddress.setBounds(259, 241, 223, 19);

        unmarried.setBackground(new java.awt.Color(0, 22, 25));
        mstatus.add(unmarried);
        unmarried.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unmarried.setForeground(new java.awt.Color(255, 255, 255));
        unmarried.setText("Unmarried");
        UI1.add(unmarried);
        unmarried.setBounds(390, 280, 89, 25);

        married.setBackground(new java.awt.Color(0, 22, 25));
        mstatus.add(married);
        married.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        married.setForeground(new java.awt.Color(255, 255, 255));
        married.setText("Married");
        UI1.add(married);
        married.setBounds(259, 282, 69, 25);

        other.setBackground(new java.awt.Color(0, 22, 25));
        gender.add(other);
        other.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        other.setForeground(new java.awt.Color(255, 255, 255));
        other.setText("Other");
        UI1.add(other);
        other.setBounds(460, 200, 62, 25);

        state.setBackground(new java.awt.Color(0, 22, 25));
        state.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        state.setForeground(new java.awt.Color(255, 255, 255));
        state.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        state.setCaretColor(new java.awt.Color(30, 79, 36));
        state.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UI1.add(state);
        state.setBounds(259, 465, 223, 19);

        address.setBackground(new java.awt.Color(0, 22, 25));
        address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        address.setCaretColor(new java.awt.Color(30, 79, 36));
        address.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UI1.add(address);
        address.setBounds(259, 327, 223, 19);

        pcode.setBackground(new java.awt.Color(0, 22, 25));
        pcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pcode.setForeground(new java.awt.Color(255, 255, 255));
        pcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pcode.setCaretColor(new java.awt.Color(30, 79, 36));
        pcode.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UI1.add(pcode);
        pcode.setBounds(259, 419, 223, 19);

        city.setBackground(new java.awt.Color(0, 22, 25));
        city.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        city.setForeground(new java.awt.Color(255, 255, 255));
        city.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        city.setCaretColor(new java.awt.Color(30, 79, 36));
        city.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UI1.add(city);
        city.setBounds(259, 374, 223, 19);

        jPanel5.setBackground(new java.awt.Color(30, 79, 36));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Next");
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        worning.setForeground(new java.awt.Color(255, 0, 0));
        worning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        worning.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(120, 39));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MINUS.PNG"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CANCEL.PNG"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout UILayout = new javax.swing.GroupLayout(UI);
        UI.setLayout(UILayout);
        UILayout.setHorizontalGroup(
            UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UILayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UILayout.createSequentialGroup()
                        .addComponent(UI1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UILayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(UILayout.createSequentialGroup()
                .addGroup(UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UILayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(worning, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UILayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        UILayout.setVerticalGroup(
            UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UILayout.createSequentialGroup()
                .addGroup(UILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UILayout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(UILayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(worning, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UI1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(UI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(UI, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

             public void CreateCursor()
    {
        Toolkit toolkit=Toolkit.getDefaultToolkit();
        Image img=toolkit.getImage("CC4.png");
        Point point=new Point(0,0);
        Cursor cursor=toolkit.createCustomCursor(img, point,"CC4");
       
        this.setCursor(cursor);
     
        jLabel20.setCursor(cursor);
        jLabel21.setCursor(cursor);
        jLabel22.setCursor(cursor);
        jLabel23.setCursor(cursor);
        jLabel24.setCursor(cursor);
        jLabel25.setCursor(cursor);
        jLabel26.setCursor(cursor);
        jLabel27.setCursor(cursor);
        jLabel28.setCursor(cursor);
        jLabel2.setCursor(cursor);
        jLabel29.setCursor(cursor);
        jLabel30.setCursor(cursor);
        jPanel1.setCursor(cursor); 
        jPanel6.setCursor(cursor);
        appno.setCursor(cursor);
        jLabel31.setCursor(cursor);
        jLabel32.setCursor(cursor);
        jLabel33.setCursor(cursor);  
      
    }
    
    public void createHandCursor()
    {
       Toolkit t=Toolkit.getDefaultToolkit();
        Image i=t.getImage("CC3.png");
        Point p=new Point(0,0);
        Cursor c=t.createCustomCursor(i, p,"CC3");
        jLabel8.setCursor(c);
        jLabel9.setCursor(c);
        jLabel34.setCursor(c);
        name.setCursor(c);
        
        fname.setCursor(c);
        day.setCursor(c);
        month.setCursor(c);
        year.setCursor(c);
        male.setCursor(c);
        female.setCursor(c);
        jPanel5.setCursor(c);
        married.setCursor(c);
        unmarried.setCursor(c);
        other.setCursor(c);
        eaddress.setCursor(c);
        pcode.setCursor(c);
        address.setCursor(c);
        city.setCursor(c);
        state.setCursor(c);
        
        
    }
    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
         jPanel5.setBackground(new Color(18, 46, 21));
      
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
         jPanel5.setBackground(new Color(45, 119, 54)); 
        if(name.getText().equals(""))
          worning.setText("Please enter your Name!!");else {
                if(fname.getText().equals(""))
                worning.setText("Please enter your father name!!");else {
                        if(day.getSelectedItem().equals("0")&&month.getSelectedItem().equals("0")&&year.getSelectedItem().equals("0000"))
                         worning.setText("Please select your Date of birth!!");else{
                            if(!male.isSelected()&&!female.isSelected()&&!other.isSelected())
                            worning.setText("Please select Your Gender!!");else {               
                                if(eaddress.getText().equals(""))
                                 worning.setText("Please enter your E-mail!!");else {
                                       if(!married.isSelected()&&!unmarried.isSelected())
                                        worning.setText("Please select your marital Status!!");else { 
                                            if(address.getText().equals(""))
                                            worning.setText("Please enter your Address!!");else {
                                                if(city.getText().equals(""))
                                                worning.setText("Please enter your City!!");else {
                                                        if(pcode.getText().equals(""))
                                                         worning.setText("Please enter your Pin code!!");else {
                                                                if(state.getText().equals(""))
                                                                    worning.setText("Please enter your state!!");
                                                                           else {
                                                                                 
                                                                                 pb.setName(name.getText());
                                                                                 pb.setFathername(fname.getText());
                                                                                 pb.setDay((String)day.getSelectedItem());
                                                                                 pb.setMonth((String)month.getSelectedItem());
                                                                                 pb.setYear((String)year.getSelectedItem());
                                                                                 pb.setEmail(eaddress.getText());
                                                                                 pb.setPcode(pcode.getText());
                                                                                 pb.setCity(city.getText());
                                                                                 pb.setState(state.getText());
                                                                                 pb.setAddress(address.getText());
                                                                                 if(male.isSelected())
                                                                                     pb.setGender(male.getText());
                                                                                 else
                                                                                     pb.setGender(female.getText());
                                                                                 
                                                                                 if(married.isSelected())
                                                                                 {
                                                                                     pb.setMaritalstatus(married.getText());
                                                                                 }
                                                                                  if(unmarried.isSelected())
                                                                                 {
                                                                                     pb.setMaritalstatus(unmarried.getText());
                                                                                 }
                                                                                   if(other.isSelected())
                                                                                 {
                                                                                     pb.setGender(other.getText());
                                                                                 }
                                                                                         
                                                               
                                                                                  
                                                                                  Additional ai=new Additional();
                                                                                  ai.setVisible(true);
                                                                                  ai.setPB(pb);
                                                                                 ai.setCon(con);
                                                                                  this.setVisible(false);
                                                                
                                                                              }
                                                                         }
                                                                   }
                                                               }
                                                           }
                                                       }
                                                  }    
                                            }
                                      }
             }
    }//GEN-LAST:event_jPanel5MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            ResultSet rs=null;
            Statement smt=null;
            
            smt=con.createStatement();
            rs=smt.executeQuery("select *from user;");
            
            while(rs.next())
            {
                num=rs.getInt("number");   
            }
            num++;
            appno.setText(num+"");
            pb.setNum(num);
        } catch (SQLException ex) {
            Logger.getLogger(PersonalDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_formWindowOpened

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setState(LogIn.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
       jPanel5.setBackground(new Color(45, 119, 54));
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
       jPanel5.setBackground(new Color(30,79,36));
    }//GEN-LAST:event_jPanel5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private atmsimulator.UI UI;
    private atmsimulator.UI UI1;
    private javax.swing.JTextField address;
    private javax.swing.JLabel appno;
    private javax.swing.JTextField city;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JTextField eaddress;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton married;
    private javax.swing.JComboBox<String> month;
    private javax.swing.ButtonGroup mstatus;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton other;
    private javax.swing.JTextField pcode;
    private javax.swing.JTextField state;
    private javax.swing.JRadioButton unmarried;
    private javax.swing.JLabel worning;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
